layout_spectrum: 0.202509
color:
  saturation: 0.05555556
  lightness: 0.953405
  brandStrength: 0.3458781
  brandColors:
    - '#302E2F'
    - '#393877'
    - '#D1C6C6'
    - '#4B5CA4'
    - '#4A5C42'
  rhythmicContrast: 0
typography_spectrum: 0.5179211
name: Brett Cohrs
